# https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-config-file/

apiVersion: v1
kind: Secret 
metadata:
  name: mongodb-secret
  namespace: dev
type: Opaque
data:
  mongo-root-username: cm9vdA==       #echo -n 'root' | base64
  mongo-root-password: cGFzc3dvcmQ=   #echo -n 'password' | base64


